- name: Get sw-cli-tools folder
  tags: shopware
  stat: path="{{ shopware_sw_directory }}"
  register: swcliDirectory

- name: Ensure git is installed
  tags: shopware
  apt: name=git state=present
  when: swcliDirectory.stat.isdir is not defined or not swcliDirectory.stat.isdir

- name: Set Github Oauth Token for composer update
  tags: shopware
  command: composer config --global github-oauth.github.com {{ shopware_github_token }}
  when: swcliDirectory.stat.isdir is not defined or not swcliDirectory.stat.isdir

- name: Clone repository sw-cli-tools from Github
  tags: shopware
  git: repo=https://github.com/shopwareLabs/sw-cli-tools.git dest="{{ shopware_sw_directory }}" recursive=false ssh_opts="-o StrictHostKeyChecking=no"
  when: swcliDirectory.stat.isdir is not defined or not swcliDirectory.stat.isdir

- name: Check for vendor folder in sw-cli-tools
  tags: shopware
  stat: path="{{ shopware_sw_directory }}/vendor"
  register: swVendorDirectory

- name: Download sw-cli-tools dependencies
  tags: shopware
  command: composer -n install chdir="{{ shopware_sw_directory }}"
  environment:
    HOME: "/root"
  when: swVendorDirectory.stat.isdir is not defined or not swVendorDirectory.stat.isdir

- name: Set sw-cli-tools symlink
  file: src="{{ shopware_sw_directory }}/bin/{{ shopware_sw_executable }}" dest="/usr/bin/{{ shopware_sw_executable }}" state=link
  when: swVendorDirectory.stat.isdir is not defined or not swVendorDirectory.stat.isdir
